### PR TITLE
Support progress indicators using tqdm

### PR DESCRIPTION
**Pull request by tillahoffmann**
[`tqdm`](https://pypi.python.org/pypi/tqdm) is a progress bar indicator for python. This PR adds the `tqdm` keyword argument to `VB.update`. For example,

```python
from tqdm import tqdm  # or tqdm_notebook in a jupyter notebook

Q = build_model()
Q.update(repeat=100, tqdm=tqdm)
```

This does not introduce a dependence on tqdm because the user needs to import manually.

### CODE REVIEW

**Comment by jluttine** [comment]
Nice! Didn't know about tqdm. I'll try this out soon. :+1: At the moment, it might break some unit tests or documentation tests that depend on what the VB iteration prints out, so I need to check those too.

**Comment by tillahoffmann** [comment]
Great! `tqdm` prints to `stderr` by default so hopefully it won't break anything.

**Comment by jluttine** [comment]
Does this work with case `repeat=None`?

**Comment by jluttine** [comment]
Thanks, I tested and it works nicely. This shouldn't affect the tests in any way because tqdm is None by default.

**Pull request merged**
