### PR TITLE
Functional tests for plotting

### PR DESCRIPTION
**Pull request by dancek**
I tried my hand at writing some tests that create plots. These obviously aren't unit tests (and it would be difficult to make any). I understand very little about what `bayespy` is used for, so I used the examples from documentation. Anyway, these tests would make sure that some basic use cases work after any code change.

I hope the tests pass on different platforms. :)

### CODE REVIEW

**Comment by dancek** [comment]
It looks to me like the Travis build didn't even run the tests before failing. Maybe you can manually initiate another Travis build or try running these tests on your local machine?

**Comment by jluttine** [comment]
I think the first run failed because of temporary pypi problem but the two other runs seem to fail on the contour test. I don't know why because the tests pass on my machine..

**Comment by dancek** [comment]
For some reason I only see 10000 lines of log in https://travis-ci.org/bayespy/bayespy/jobs/50995830 .

Where did you see the test run log?

**Comment by dancek** [comment]
It'd be great to see the actual plot in `result_images/test_plot/contour.png`. Maybe there are some minor font differences?

**Comment by jluttine** [comment]
For instance, https://s3.amazonaws.com/archive.travis-ci.org/jobs/50995829/log.txt
In upper right corner there is a button to download the full log.

**Comment by dancek** [comment]
I'm really surprised that the others pass while one of the plots fails. Of course the easy way out is to just remove the individual test. I guess I'll do that for now...

**Comment by jluttine** [comment]
Yep, you could comment out that test and I'll examine it later. I also pull requested to remove show() just in case it has any effects. At least, if nosetests are not run in the root folder, show() causes a figure window to pop up and stop the tests until the window is closed.

**Comment by dancek** [comment]
I just realized you have the scheme of marking commits with tags such as `TST`. Should I rewrite the commit messages (and maybe squash out the merge) before you merge this?

**Comment by jluttine** [comment]
It's ok, your commit message are clean. :) And thanks a LOT for these unit tests! I've been thinking that I should write something like these, so these are really great. :)

**Comment by dancek** [comment]
I see that `dancek-plot-tests` passed. You're probably better off merging that than this pull request.

https://travis-ci.org/bayespy/bayespy/builds/51053647

**Comment by jluttine** [comment]
Done, thanks!

**Pull request closed without merging**
